In [9]:
import numpy as np

In [30]:
#读取文件
file_path="./US_video_data_numbers.csv"

t1=np.loadtxt(file_path,delimiter=",",dtype="int")
print(t1)

[[4394029  320053    5931   46245]
 [7860119  185853   26679       0]
 [5845909  576597   39774  170708]
 ...
 [ 142463    4231     148     279]
 [2162240   41032    1384    4737]
 [ 515000   34727     195    4722]]


In [31]:
#numpy中的转置
t2=np.arange(24).reshape(4,6)
print(t2)
print(t2.T)
#t2.transpose()
#t2.swapaxes(1,0)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [32]:
#取行 包括取连续的t2[2:]和不连续的t2[[0,2]]
print(t2[2])

#取列
print(t2[:,0])

[12 13 14 15 16 17]
[ 0  6 12 18]


In [34]:
#三元运算符
t=np.arange(24).reshape((4,6))
print(t)

t1=np.where(t<10,0,1)
print(t1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0 0 0 0 0 0]
 [0 0 0 0 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
