In [13]:
import numpy as np
import random

In [14]:
#三种创建方法
t1 = np.array([1,2,3])
print(t1)
print(type(t1))

t2=np.array(range(3))
print(t2)
print(type(t2))

t3=np.arange(3)
print(t3)
print(type(t3))


[1 2 3]
<class 'numpy.ndarray'>
[0 1 2]
<class 'numpy.ndarray'>
[0 1 2]
<class 'numpy.ndarray'>


In [18]:
#数据类型
t4=np.array(range(1,4),dtype=float)
print(t4)
print(t4.dtype)

t5=np.array([1,0,0,1,0],dtype=bool)
print(t5)
print(t5.dtype)

#调整数据类型
t6=t5.astype("int8")
print(t6.dtype)

#numpy中的小数
t7=np.array([random.random() for i in range(10)])
print(t7)

#保留小数位数
t8=np.round(t7,2)
print(t8)

[1. 2. 3.]
float64
[ True False False  True False]
bool
int8
[0.23380258 0.94542137 0.42916329 0.95836449 0.09721448 0.36983881
 0.65942792 0.48230406 0.94893093 0.23922105]
[0.23 0.95 0.43 0.96 0.1  0.37 0.66 0.48 0.95 0.24]
